/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIs;

import Main.DonationManagementSystem;
import Project.Project;

/**
 *
 * @author muhammadkhuramniaz
 */
public class WelcomeScreen extends javax.swing.JFrame {

    /**
     * Creates new form WelcomeScreen
     */
    public WelcomeScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        addProject = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        setTeamLeader = new javax.swing.JButton();
        allocateTeam = new javax.swing.JButton();
        removeTeam = new javax.swing.JButton();
        replaceTeam = new javax.swing.JButton();
        addDonor = new javax.swing.JButton();
        addApplicant = new javax.swing.JButton();
        shortlist = new javax.swing.JButton();
        searchProject = new javax.swing.JButton();
        issue = new javax.swing.JButton();
        searchBeneficiery = new javax.swing.JButton();
        seachDonor = new javax.swing.JButton();
        load = new javax.swing.JButton();
        sync = new javax.swing.JButton();
        addVolunteer = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(700, 400));

        addProject.setText("Add New Project");
        addProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProjectActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Silom", 0, 26)); // NOI18N
        jLabel1.setText("Welcome to Donation Management System");

        setTeamLeader.setText("Set Team Leader");
        setTeamLeader.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setTeamLeaderActionPerformed(evt);
            }
        });

        allocateTeam.setText("Allocate Team");
        allocateTeam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allocateTeamActionPerformed(evt);
            }
        });

        removeTeam.setText("Remove Team");
        removeTeam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeTeamActionPerformed(evt);
            }
        });

        replaceTeam.setText("Replace Team");
        replaceTeam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                replaceTeamActionPerformed(evt);
            }
        });

        addDonor.setText("Add Donor");
        addDonor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDonorActionPerformed(evt);
            }
        });

        addApplicant.setText("Add Applicant");
        addApplicant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addApplicantActionPerformed(evt);
            }
        });

        shortlist.setText("Shortlist Applicants");
        shortlist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shortlistActionPerformed(evt);
            }
        });

        searchProject.setText("Search Project");
        searchProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchProjectActionPerformed(evt);
            }
        });

        issue.setText("Issue Funding");
        issue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issueActionPerformed(evt);
            }
        });

        searchBeneficiery.setText("Search Beneficiery");
        searchBeneficiery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBeneficieryActionPerformed(evt);
            }
        });

        seachDonor.setText("Search Donor");
        seachDonor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seachDonorActionPerformed(evt);
            }
        });

        load.setText("Load");
        load.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadActionPerformed(evt);
            }
        });

        sync.setText("Sync Changes");
        sync.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                syncActionPerformed(evt);
            }
        });

        addVolunteer.setText("Add Volunteer");
        addVolunteer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addVolunteerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(122, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(113, 113, 113))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(addVolunteer, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(addProject, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(setTeamLeader, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(allocateTeam, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(addApplicant, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(removeTeam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(replaceTeam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(addDonor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(shortlist, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(searchProject, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(issue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(searchBeneficiery, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                                    .addComponent(seachDonor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(load, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(sync, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(138, 138, 138))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addProject)
                    .addComponent(removeTeam)
                    .addComponent(searchProject))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(setTeamLeader)
                    .addComponent(replaceTeam)
                    .addComponent(issue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(allocateTeam)
                    .addComponent(addDonor)
                    .addComponent(searchBeneficiery))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addApplicant)
                    .addComponent(shortlist)
                    .addComponent(seachDonor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sync)
                    .addComponent(load)
                    .addComponent(addVolunteer))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProjectActionPerformed
        // TODO add your handling code here:
        AddProject addProject = new AddProject();       
        addProject.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_addProjectActionPerformed

    private void setTeamLeaderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setTeamLeaderActionPerformed
        // TODO add your handling code here:
        SetTeamLeader stl = new SetTeamLeader();
        stl.setVisible(true);
        stl.setProjects();
        this.setVisible(false);
        
    }//GEN-LAST:event_setTeamLeaderActionPerformed

    private void allocateTeamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allocateTeamActionPerformed
        // TODO add your handling code here:
        AllocateTeam allocateTeam = new AllocateTeam();
        allocateTeam.setVisible(true);
        this.setVisible(false);
        allocateTeam.setProjects();
        allocateTeam.setVolunteers();
        
    }//GEN-LAST:event_allocateTeamActionPerformed

    private void removeTeamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeTeamActionPerformed
        // TODO add your handling code here:
        RemoveTeam removeTeam = new RemoveTeam();
        removeTeam.setVisible(true);
        this.setVisible(false);
        removeTeam.setProjects();
    }//GEN-LAST:event_removeTeamActionPerformed

    private void replaceTeamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_replaceTeamActionPerformed
        // TODO add your handling code here:
        ReplaceTeam replaceTeam = new ReplaceTeam();
        replaceTeam.setVisible(true);
        this.setVisible(false);
        replaceTeam.setProjects();
    }//GEN-LAST:event_replaceTeamActionPerformed

    private void addDonorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDonorActionPerformed
        // TODO add your handling code here:
        AddDonor addDonor = new AddDonor();
        addDonor.setVisible(true);
        this.setVisible(false);
        addDonor.setProjects();
        
    }//GEN-LAST:event_addDonorActionPerformed

    private void addApplicantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addApplicantActionPerformed
        // TODO add your handling code here:
        AddApplicant addApplicant = new AddApplicant();
        addApplicant.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_addApplicantActionPerformed

    private void shortlistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shortlistActionPerformed
        // TODO add your handling code here:
        ShortList shortList = new ShortList();
        shortList.setVisible(true);
        this.setVisible(false);
        shortList.setApplicants();
    }//GEN-LAST:event_shortlistActionPerformed

    private void searchProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchProjectActionPerformed
        // TODO add your handling code here:
        SearchProject searchProject = new SearchProject();
        searchProject.setVisible(true);
        this.setVisible(false);
        searchProject.set();
    }//GEN-LAST:event_searchProjectActionPerformed

    private void issueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issueActionPerformed
        // TODO add your handling code here:
        IssueFunding issueFunding = new IssueFunding();
        issueFunding.setVisible(true);
        this.setVisible(false);
        issueFunding.setProjects();
        issueFunding.setApplicants();
    }//GEN-LAST:event_issueActionPerformed

    private void searchBeneficieryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBeneficieryActionPerformed
        // TODO add your handling code here:
        SearchBneficiery searchBneficiery = new SearchBneficiery();
        searchBneficiery.setVisible(true);
        this.setVisible(false);
        searchBneficiery.set();
    }//GEN-LAST:event_searchBeneficieryActionPerformed

    private void seachDonorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seachDonorActionPerformed
        // TODO add your handling code here:
        SearchDonor searchDonor = new SearchDonor();
        searchDonor.setVisible(true);
        this.setVisible(false);
        searchDonor.set();
        
    }//GEN-LAST:event_seachDonorActionPerformed

    private void loadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadActionPerformed
        // TODO add your handling code here:
        dms.loadFromDB();
        
    }//GEN-LAST:event_loadActionPerformed

    private void syncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_syncActionPerformed
        // TODO add your handling code here:
        dms.syncChanges();
    }//GEN-LAST:event_syncActionPerformed

    private void addVolunteerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addVolunteerActionPerformed
        // TODO add your handling code here:
        AddVolunteer addVolunteer = new AddVolunteer();
       addVolunteer.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_addVolunteerActionPerformed

    /**
     * @param args the command line arguments
     * 
     */
    
    DonationManagementSystem dms = new DonationManagementSystem();
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WelcomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WelcomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WelcomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WelcomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WelcomeScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addApplicant;
    private javax.swing.JButton addDonor;
    private javax.swing.JButton addProject;
    private javax.swing.JButton addVolunteer;
    private javax.swing.JButton allocateTeam;
    private javax.swing.JButton issue;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton load;
    private javax.swing.JButton removeTeam;
    private javax.swing.JButton replaceTeam;
    private javax.swing.JButton seachDonor;
    private javax.swing.JButton searchBeneficiery;
    private javax.swing.JButton searchProject;
    private javax.swing.JButton setTeamLeader;
    private javax.swing.JButton shortlist;
    private javax.swing.JButton sync;
    // End of variables declaration//GEN-END:variables
}
